import { CUSTOM_ICONS_COUNTRIES as country } from "../const/icons";

export const countries = [
  { country: "United Arab Emirates", code: "AE", flag: country.unitedArabEmirates32p },
  { country: "Argentina", code: "ar", flag: country.argentina32p },
  { country: "Austria", code: "at", flag: country.austria32p },
  { country: "Australia", code: "au", flag: country.australia32p },
  { country: "Belgium", code: "be", flag: country.belgium32p },
  { country: "Bulgaria", code: "bg", flag: country.bulgaria32p },
  { country: "Brazil", code: "br", flag: country.brazil32p },
  { country: "Canada", code: "ca", flag: country.canada32p },
  { country: "Switzerland", code: "ch", flag: country.switzerland32p },
  { country: "China", code: "cn", flag: country.china32p },
  { country: "Colombia", code: "co", flag: country.colombia32p },
  { country: "Cuba", code: "cu", flag: country.cuba32p },
  { country: "Czech Republic", code: "cz", flag: country.czechRepublic32p },
  { country: "Germany", code: "de", flag: country.germany32p },
  { country: "Egypt", code: "eg", flag: country.egypt32p },
  { country: "France", code: "fr", flag: country.france32p },
  { country: "United Kingdom", code: "gb", flag: country.unitedKingdom32p },
  { country: "Greece", code: "gr", flag: country.greece32p },
  { country: "Hong Kong", code: "hk", flag: country.hongKong32p },
  { country: "Hungary", code: "hu", flag: country.hungary32p },
  { country: "Indonesia", code: "id", flag: country.indonesia32p },
  { country: "Ireland", code: "ie", flag: country.ireland32p },
  { country: "Israel", code: "il", flag: country.israel32p },
  { country: "India", code: "in", flag: country.india32p },
  { country: "Italy", code: "it", flag: country.italy32p },
  { country: "Japan", code: "jp", flag: country.japan32p },
  { country: "South Korea", code: "kr", flag: country.southKorea32p },
  { country: "United States", code: "us", flag: country.usa32p },
  // { country: "Chile", code: "cl", flag: country.chile32p },
];